Updated Homework #2 and Design Warm-Up #1 for 2021
uchicago-cs/cmsc22000 pull request #36
Opened 2021-04-01 16:07 UTC by borjasotomayor

Homework #2 and Design Warm-Up #1 have only undergone some minor updates, mostly to update some terminology (lab vs homework, master vs main, etc.). For Homework #2 I also made a minor change to the starter code (see https://github.com/uchicago-cmsc22000/hw2-starter-code/commit/90eae34db98e1bc86b644ab84e8f64f19030fa31), and verified the code compiles correctly in the department's new Ubuntu 20.04 environment.

2021-04-05 20:50 UTC, lilyehsani requested changes
I made some minor comments about missing punctuation for clarity. Overall, the writeup looks great and compiles in the CSIL Linux environment (I ran `make`, `make samples`, `sample/polygon.h`, and `make tests`). I believe everything is written clearly and I do not anticipate any specific questions that we could address further.

2021-04-05 20:50 UTC, lilyehsani commented on website/hw/hw2.rst
> +repository called ``2021-hw2-GITHUB_USERNAME``` inside our
There is an extra ` after USERNAME

2021-04-05 20:50 UTC, lilyehsani commented on website/hw/hw2.rst
> +-  A Polygon module (``include/polygon.h' and ``src/polygon.c``) that
This line is missing a `` after polygon.h'

2021-04-05 20:50 UTC, lilyehsani commented on website/project/warmup.rst
> +expect to use)
Missing a period end of this line

2021-04-05 20:50 UTC, lilyehsani commented on website/project/warmup.rst
> +      moves to position (x1, y1)
Missing a question mark end of this line

2021-04-05 20:50 UTC, lilyehsani commented on website/project/warmup.rst
> +           Return 0;
I think the r in ``Return`` should be lowercase here

2021-04-06 14:53 UTC, firatciftci commented on website/project/warmup.rst
> +What’s that you say? There’s a lot of chess games out there already? Ah,
I think this should be changed to "There are a lot of chess games..."

2021-04-06 15:00 UTC, firatciftci requested changes
I've added a comment mentioning a small grammatical request, but apart from that everything seems to be good to go!

2021-04-07 19:14 UTC, borjasotomayor commented
Thanks, I've pushed the fixes you suggested.

2021-04-08 00:52 UTC, merged